### ISSUE TITLE
Where is source for Hangfire.Web?

### ISSUE THREAD

**Issue by evenkiel** [odinserj/odinserj.net#1]
Hi there. Loving your library. Really simple to use.

I'm running into a situation with my asp.net app where multiple servers get created when I stop/start the site. I'd like to control this better and ensure that there's only a single server for my app.

I went to look at the source for AspNetBackgroundJobServer and discovered that I couldn't find the source for Hangfire.Web. Can you point me in the right direction?

Thanks!

**Comment by odinserj** [comment]
Hello, @evenkiel. There is no more `HangFire.Web` assembly. Hangfire Dashboard in `1.0.0-alpha1` implemented as OWIN middleware (see [this PR](https://github.com/odinserj/HangFire/pull/128)), and since OWIN dependencies are very lightweight, `HangFire.Web` was merged with `HangFire.Core`. If you need to get the sources of previous version, you can look [here](https://github.com/odinserj/HangFire/tree/v0.9.1).

> I'm running into a situation with my asp.net app where multiple servers get created when I stop/start the site. I'd like to control this better and ensure that there's only a single server for my app.

Does your app reside in the web farm / web garden environment?

**Comment by evenkiel** [comment]
Thanks for the quick response.

I see now that I am using 0.91 in my app (via nuget), but was looking at the latest source. That explains my disconnect.

My app is small and is currently running inside iisexpress on my dev machine. I find that if I stop the site abruptly, which I do often during dev, and then start it back up, that a new server will be created. While the Dashboard allows you to manage/delete jobs it doesn't allow you manage servers. With 0.91 what would be my best approach for ensuring that only one server gets spun up, or removing other duplicate servers?

Thanks!

**Comment by odinserj** [comment]
> With 0.91 what would be my best approach for ensuring that only one server gets spun up, or removing other duplicate servers?

Just don't do anything, and it will be removed from the list automatically after some time (there is the [`ServerWatchdog`](https://github.com/odinserj/HangFire/blob/master/src/HangFire.Core/Server/ServerWatchdog.cs) class that removes obsolete server records). If you want to ensure only one job server instance is running, control the host instance. Single host instance – single job server (if you don't create other server instances in your code). Overlapped App Pool Recycle is also being handled – by a [global mutex](https://github.com/odinserj/HangFire/blob/master/src/HangFire.Core/Server/ServerBootstrapper.cs#L53).

**Comment by evenkiel** [comment]
Excellent. Thanks!

**Comment by odinserj** [comment]
One note. If you host job server inside a web app, it is being aborted with the main web application. It does not create separate processes, and there is no magic. What you see is an obsolete record in a storage that was not deleted by job server because it was terminated ungracefully. Hangfire knows that this may happen and perform the compensation logic automatically, but only after timeout.
