### ISSUE TITLE
Guide to implement custom HangFire storage?

### ISSUE THREAD

**Issue by luuhq** [odinserj/odinserj.net#3]
Hello!

First of all, thanks for the fantastic library!

Is there a guide to implement custom job storage for HangFire? I want to use it with Azure Queue, without SQL Server (or replacing it with Azure Table).

Regards!
Steven

**Comment by odinserj** [comment]
@sluu99, thanks for the good words. Unfortunately, Hangfire can work only side-by-side with persistent storage. Queues usually do not provide the key tools for enough transparency, and peeking items one by one is not a good solution. This implementation was chosen because I personally don't like background jobs (and consider them as a necessary evil) – it is very hard sometimes to know what exactly is going on.

You can use Hangfire with [Redis storage](http://docs.hangfire.io/en/latest/users-guide/storage-configuration/using-redis.html) in Azure environment – recently I've heard that Redis is supported, but to be honest with you, I'm not sure Azure configuration can suit Hangfire needs – need to test it, because it is called _Redis Cache_ in Azure.

If you really can not use SQL Server, you can also take a look at [WebJobs](http://www.hanselman.com/blog/IntroducingWindowsAzureWebJobs.aspx).

**Comment by doug-thinkingcap** [comment]
Has this moved forward in the last year? Any more info on ability to use Azure Redis?

**Comment by nkosi23** [comment]
Me I'm mainly interested in the "guide to implement a custom storage" part

**Comment by Corstiaan84** [comment]
+1 for the custom storage guide

**Comment by farax** [comment]
Custom storage would be good to have.
