### ISSUE TITLE
Implementation Question

### ISSUE THREAD

**Issue by a-shawky** [odinserj/odinserj.net#4]
HI,

kindly I want to know which classes in Hangfire source code that is responsible for keeping the background tasks a live against ASP.net app domain shutdown?

**Comment by odinserj** [comment]
Hello,

Hangfire uses persistent storage to keep information about background jobs. [Hangfire.Core/Storage](https://github.com/HangfireIO/Hangfire/tree/master/src/Hangfire.Core/Storage) folder contain abstractions to be able to use different storage implementations. Here is an [example implementation](https://github.com/HangfireIO/Hangfire/tree/master/src/Hangfire.SqlServer) using SQL Server 2008+.

**Comment by a-shawky** [comment]
Thanks for you Kind and Fast response, I was asking about how HangFire stand against appdomian shutdown, if there a class like "Hangfire.Core\Server\ServerHeartbeat.cs" that keeps the appdomian running, I know that Hangfire can use mutible data Storage to store jobs info, but what hangfire do if the application shut down due to no requests and prevent its background threads from shutdown, is it done by code or a configuration to IIS?

**Comment by odinserj** [comment]
Hangfire does not prevent application from shutdown – it is a library and should not affect your application environment. But you can do it manually and here is [how to make your ASP.NET application always running](http://docs.hangfire.io/en/latest/deployment-to-production/making-aspnet-app-always-running.html).

Instead of affecting the environment, Hangfire is ready to unexpected shutdowns on any line of code. You can kill the process from the task manager and be sure that terminated background jobs will be processed after application restart sooner or later.

**Comment by a-shawky** [comment]
many thanks for your kind, clear and fast response, have a nice day.

**Comment by odinserj** [comment]
Thank you too! Btw, there is [Hangfire Forum](http://discuss.hangfire.io) (there was a problem with its unavailability, it is fixed now). Closing the issue.

**Comment by a-shawky** [comment]
I tried to post my question on the Forum, but it was not working.
thanks.
